apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todoui
  name: todoui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todoui
        tier: frontend
    spec:
      containers:
      - image: maeddes/todoui-thymeleaf:hse24patched
        env:
        - name: BACKEND_URL
          value: "http://todobackend:8080"
        name: lab
        resources: {}
status: {}
