apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todobackend
  name: todobackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todobackend
    spec:
      containers:
      - image: maeddes/todobackend:hse24patched
        resources:
          limits:
            cpu: "1"
            memory: 1G
        name: todobackend
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /todos/
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 2
status: {}
