version: '3.8'
services:
  mongo:
    image: mongo
    networks:
      - todonet
    ports:
      - "27017:27017"
  
  nodebackend:
    build: ./todo-backend
    networks:
      - todonet
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  todoui-thymeleaf:
    build:
      context: ./todoui-thymeleaf
      dockerfile: Dockerfile
    networks:
      - todonet
    ports:
      - "8090:8090"
    environment:
      - BACKEND_URL=http://nodebackend:3000/

networks:
  todonet:
