apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: todo-app
spec:
  selector:
    matchLabels:
      app: node-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: your-dockerhub-username/todo-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/todos"
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend
  namespace: todo-app
spec:
  ports:
    - port: 3000
  selector:
    app: node-backend
