apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  rules:
    - host: todo.example.com
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: nodebackend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todoui-thymeleaf
                port:
                  number: 8090
