apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-app
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/todoui-thymeleaf:latest
          ports:
            - containerPort: 8090
          env:
            - name: BACKEND_URL
              value: "http://haproxy:80/"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todo-app
spec:
  type: LoadBalancer
  ports:
    - port: 8090
  selector:
    app: frontend
